### ISSUE TITLE
subscriber error

### ISSUE THREAD

**Issue by sys-met** [dusty-nv/ros_deep_learning#106]
Hello dusty-nv
I want to receive data with a simple subscriber node, but I am getting the following error
  
 rospy.loginfo("Robot şarjı: %f"%mesaj.bbox.center.x)
AttributeError: 'Detection2DArray' object has no attribute 'bbox'

**Comment by dusty-nv** [comment]
Hi @sys-met, see here for the specification of the `Detection2DArray` message:  http://docs.ros.org/en/lunar/api/vision_msgs/html/msg/Detection2DArray.html

I think you probably need to index it to get the `Detection2D` message that you are looking for.

**Comment by sys-met** [comment]
Hello dusty-nv
i need a simple example on this

 rospy.loginfo(detections[0].bbox.size_y)
TypeError: 'Detection2DArray' object does not support indexing

**Comment by sys-met** [comment]
thanks, it worked
