### ISSUE TITLE
Ros Noetic, undefined symbol, Jetson AGX, Jetpack 5.1

### ISSUE THREAD

**Issue by Michsh** [dusty-nv/ros_deep_learning#114]
Hi,
I get this error: 
**ros_workspace/devel/lib/ros_deep_learning/detectnet: undefined symbol: _ZN9detectNet18NetworkTypeFromStrEPKc**
when i try to run 
./ros_workspace/devel/lib/ros_deep_learning/detectnet or with roslaunch

Need help, its`s a fresh install of jetpack. 
Thanks !

**Comment by dusty-nv** [comment]
OK, this should be fixed in ros_deep_learning master now.
