### ISSUE TITLE
no package ros_deep_learning in docker container ros-noetic-pytorch-l4t-32.7.1

### ISSUE THREAD

**Issue by lenhatquang2512** [dusty-nv/ros_deep_learning#115]
Hi, thank you for your repo.

I am using Jetson Nano with latest Jetpack 4.6.3 (L4T R32.7.1) so when I run your **`docker/run.sh -ros=noetic`** (I have also tried foxy as well, but same error l), it automatically installed docker image **ros-noetic-pytorch-l4t-r32.7.1**. But when I tried to test with `roslaunch`, it said there was no package name **"ros_deep_learning"**. Can you update this docker container of version r32.7.1 so that it contains pre-built of ros_deep_learning ? Thank you.

**Comment by dusty-nv** [comment]
@lenhatquang2512, sorry yes - I will kick of the builds to re-build these containers

**Comment by lenhatquang2512** [comment]
Thank you for your message. Actually I noticed that you have a **ros1** branch of this repo. So I decided to build your package from source with ROS **melodic**. I met this error when trying `catkin_make` : `**/usr/bin/ld: cannot find -lnvbuf_utils**` . Somehow I found this same error in among the issues in your other repo - **jetbot_ros.** So as you suggested in that post, adding` link_directories(/usr/lib/aarch64-linux-gnu/tegra) ` to CMakeLists works like a charm. I tried to test with the `imageNet Node` and it worked. I think this is just my temporary fix, also the branch **ros1** is too outdated so I will still wait to try with the docker version.

**Comment by dusty-nv** [comment]
Hi @lenhatquang2512, sorry for the delay - these images have been updated on dockerhub for L4T R32.7.1 to include ros_deep_learning package:

``` bash
dustynv/ros                             galactic-pytorch-l4t-r32.7.1    8c7e49d3b27a   3 days ago      4.57GB
dustynv/ros                             foxy-pytorch-l4t-r32.7.1        d0b9f63e3b3f   3 days ago      5.01GB
dustynv/ros                             noetic-pytorch-l4t-r32.7.1      bfb0b999a3ca   3 days ago      4.13GB
```

(note that they have also been updated for L4T R35.2.1)

**Comment by lenhatquang2512** [comment]
Thank you ! I will try the Noetic image because I am more familiar with ROS1 and will let you know if there is any issue.
