### ISSUE TITLE
Format for class labels file and class colors file ?

### ISSUE THREAD

**Issue by r4hul77** [dusty-nv/ros_deep_learning#117]
Hey ! What is the correct format for class labels file and class colors file ?

**Comment by dusty-nv** [comment]
Hi @r4hul77, class labels are one name per line, like so:

```
apple
orange
banana
```

Class colors are one color per line, `r g b` or `r g b a` (alpha is optional) with values 0-255

```
255 0 0
255 127 0
255 255 0
```

**Comment by r4hul77** [comment]
perfect, Thank you so much
