### ISSUE TITLE
bbox information via the /detectnet/detections topic using a subscibrer

### ISSUE THREAD

**Issue by kleanbotmk2** [dusty-nv/ros_deep_learning#127]
Hello,

I wanted to know how I could retrieve bbox information via the /detectnet/detections topic using a subscibrer. I use a node in python under ros2 foxy. Otherwise I wanted to thank you because the package works very well!

Best regards,

Sacha

**Comment by dusty-nv** [comment]
Hi @kleanbotmk2, the message type of that topic is `vision_msgs/Detection2DArray`:

http://docs.ros.org/en/api/vision_msgs/html/msg/Detection2DArray.html

**Comment by dusty-nv** [comment]
I don't have an example of doing it with rospy, but subscribing to topics and dealing with standard messages is a typical ROS thing.   It's not a custom message type.   You can see how I construct the messages in the C++ code for the detectnet node though:

https://github.com/dusty-nv/ros_deep_learning/blob/master/src/node_detectnet.cpp

**Comment by kleanbotmk2** [comment]
okay thanks you it's working
