### ISSUE TITLE
This repo does not compile

### ISSUE THREAD

**Issue by deeprun** [dusty-nv/ros_deep_learning#25]
Could you update? This repo is no longer sync with jetson-inference. This repo does not compile

**Comment by dusty-nv** [comment]
Sorry about that, I will fix it.  For now, please use the L4T-R32.1 branch of jetson-inference repo.
________________________________

**Comment by dusty-nv** [comment]
The repo has now been updated for the latest JetPack and compiles against `jetson-inference` master.  Let me know if you have any more issues building.
